const USER_SEND_REQUEST_SEARCH_INIT = 'USER_SEND_REQUEST_SEARCH_INIT';
const USER_SEND_REQUEST_SEARCH_DONE = 'USER_SEND_REQUEST_SEARCH_DONE';
const USER_SEND_REQUEST_DETAIL_INIT = 'USER_SEND_REQUEST_DETAIL_INIT';
const USER_SEND_REQUEST_DETAIL_DONE = 'USER_SEND_REQUEST_DETAIL_DONE';

export {
  USER_SEND_REQUEST_SEARCH_INIT,
  USER_SEND_REQUEST_SEARCH_DONE,
  USER_SEND_REQUEST_DETAIL_INIT,
  USER_SEND_REQUEST_DETAIL_DONE,
};
